//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MailRes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comments.
        /// </summary>
        internal static string AddComments {
            get {
                return ResourceManager.GetString("AddComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capex.
        /// </summary>
        internal static string Budget1 {
            get {
                return ResourceManager.GetString("Budget1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man Power.
        /// </summary>
        internal static string Budget2 {
            get {
                return ResourceManager.GetString("Budget2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        internal static string Budget2_HR {
            get {
                return ResourceManager.GetString("Budget2_HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Budget3 {
            get {
                return ResourceManager.GetString("Budget3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string Budget4 {
            get {
                return ResourceManager.GetString("Budget4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By .
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capex Budget.
        /// </summary>
        internal static string CapexBudget {
            get {
                return ResourceManager.GetString("CapexBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        internal static string CostCenter {
            get {
                return ResourceManager.GetString("CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd-MMM-yyyy HH:mm:ss .
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd-MMM-yyyy.
        /// </summary>
        internal static string DateFormatShort {
            get {
                return ResourceManager.GetString("DateFormatShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivate.
        /// </summary>
        internal static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find Exel sheet with name \&apos;TEMPLATE\&apos;. Please change the sheet name..
        /// </summary>
        internal static string Err_ExelsheetName {
            get {
                return ResourceManager.GetString("Err_ExelsheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget+ has identified a conflict between the application and the environment configurations. Please contact your System Administrator to resolve this issue.
        /// </summary>
        internal static string Err_Expiry {
            get {
                return ResourceManager.GetString("Err_Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has child elements and hence cannot this {0}.
        /// </summary>
        internal static string Err_HasChild_Delete {
            get {
                return ResourceManager.GetString("Err_HasChild_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has child elements and hence any changes to this {0} is restricted. .
        /// </summary>
        internal static string Err_HasChild_Edit {
            get {
                return ResourceManager.GetString("Err_HasChild_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan should be numeric.
        /// </summary>
        internal static string Err_Month01 {
            get {
                return ResourceManager.GetString("Err_Month01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb should be numeric.
        /// </summary>
        internal static string Err_Month02 {
            get {
                return ResourceManager.GetString("Err_Month02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar should be numeric.
        /// </summary>
        internal static string Err_Month03 {
            get {
                return ResourceManager.GetString("Err_Month03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr should be numeric.
        /// </summary>
        internal static string Err_Month04 {
            get {
                return ResourceManager.GetString("Err_Month04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May should be numeric.
        /// </summary>
        internal static string Err_Month05 {
            get {
                return ResourceManager.GetString("Err_Month05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun should be numeric.
        /// </summary>
        internal static string Err_Month06 {
            get {
                return ResourceManager.GetString("Err_Month06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul should be numeric.
        /// </summary>
        internal static string Err_Month07 {
            get {
                return ResourceManager.GetString("Err_Month07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug should be numeric.
        /// </summary>
        internal static string Err_Month08 {
            get {
                return ResourceManager.GetString("Err_Month08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep should be numeric.
        /// </summary>
        internal static string Err_Month09 {
            get {
                return ResourceManager.GetString("Err_Month09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct should be numeric.
        /// </summary>
        internal static string Err_Month10 {
            get {
                return ResourceManager.GetString("Err_Month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov should be numeric.
        /// </summary>
        internal static string Err_Month11 {
            get {
                return ResourceManager.GetString("Err_Month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec should be numeric.
        /// </summary>
        internal static string Err_Month12 {
            get {
                return ResourceManager.GetString("Err_Month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        internal static string Err_NoData {
            get {
                return ResourceManager.GetString("Err_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        internal static string GrandTotal {
            get {
                return ResourceManager.GetString("GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password format!.
        /// </summary>
        internal static string InvalidePassword {
            get {
                return ResourceManager.GetString("InvalidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UserID format!.
        /// </summary>
        internal static string InvalidUserID {
            get {
                return ResourceManager.GetString("InvalidUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your last successful login was on : {0}.
        /// </summary>
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified on {0} .
        /// </summary>
        internal static string LastModBy {
            get {
                return ResourceManager.GetString("LastModBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manpower Budget.
        /// </summary>
        internal static string ManpowerBudget {
            get {
                return ResourceManager.GetString("ManpowerBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        internal static string Month01 {
            get {
                return ResourceManager.GetString("Month01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        internal static string Month02 {
            get {
                return ResourceManager.GetString("Month02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        internal static string Month03 {
            get {
                return ResourceManager.GetString("Month03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        internal static string Month04 {
            get {
                return ResourceManager.GetString("Month04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string Month05 {
            get {
                return ResourceManager.GetString("Month05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        internal static string Month06 {
            get {
                return ResourceManager.GetString("Month06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        internal static string Month07 {
            get {
                return ResourceManager.GetString("Month07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        internal static string Month08 {
            get {
                return ResourceManager.GetString("Month08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        internal static string Month09 {
            get {
                return ResourceManager.GetString("Month09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        internal static string Month10 {
            get {
                return ResourceManager.GetString("Month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        internal static string Month11 {
            get {
                return ResourceManager.GetString("Month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        internal static string Month12 {
            get {
                return ResourceManager.GetString("Month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Month_All {
            get {
                return ResourceManager.GetString("Month_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} activated successfully.
        /// </summary>
        internal static string Msg_Activate_Success {
            get {
                return ResourceManager.GetString("Msg_Activate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} activated successfully.
        /// </summary>
        internal static string Msg_ActivatSuccess {
            get {
                return ResourceManager.GetString("Msg_ActivatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inactivated successfully.
        /// </summary>
        internal static string Msg_Dectivate_Success {
            get {
                return ResourceManager.GetString("Msg_Dectivate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deactivated successfully.
        /// </summary>
        internal static string Msg_DectivatSuccess {
            get {
                return ResourceManager.GetString("Msg_DectivatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the record?.
        /// </summary>
        internal static string Msg_DeletConfirm {
            get {
                return ResourceManager.GetString("Msg_DeletConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already deleted by another user. Please check for the updated information .
        /// </summary>
        internal static string Msg_DeletError_Concurrent {
            get {
                return ResourceManager.GetString("Msg_DeletError_Concurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} you tried to delete is already used in other places. Please try Inactivate the  {0}.
        /// </summary>
        internal static string Msg_DeletError_Ref {
            get {
                return ResourceManager.GetString("Msg_DeletError_Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the record?.
        /// </summary>
        internal static string Msg_Delete_Confirm {
            get {
                return ResourceManager.GetString("Msg_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already deleted by another user. Please check for the updated information .
        /// </summary>
        internal static string Msg_Delete_Error_Concurrent {
            get {
                return ResourceManager.GetString("Msg_Delete_Error_Concurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} you tried to delete is already used in other places. Please try Inactivate the  {0}.
        /// </summary>
        internal static string Msg_Delete_Error_Ref {
            get {
                return ResourceManager.GetString("Msg_Delete_Error_Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted successfully.
        /// </summary>
        internal static string Msg_Delete_Success {
            get {
                return ResourceManager.GetString("Msg_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted successfully.
        /// </summary>
        internal static string Msg_DeletSuccess {
            get {
                return ResourceManager.GetString("Msg_DeletSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you dont have enough privilage to perform this action.
        /// </summary>
        internal static string msg_Err_Privilage {
            get {
                return ResourceManager.GetString("msg_Err_Privilage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should fill all the elements details befor forwarding.
        /// </summary>
        internal static string msg_Err_save {
            get {
                return ResourceManager.GetString("msg_Err_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Submit No Higher Role.
        /// </summary>
        internal static string msg_Err_save_MoveForward {
            get {
                return ResourceManager.GetString("msg_Err_save_MoveForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Send Back No Previous Role.
        /// </summary>
        internal static string msg_Err_save_SendBack {
            get {
                return ResourceManager.GetString("msg_Err_save_SendBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please shorten the data.
        /// </summary>
        internal static string Msg_Exceed_MaxLen {
            get {
                return ResourceManager.GetString("Msg_Exceed_MaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row to perform the required operation.
        /// </summary>
        internal static string Msg_Not_Selected {
            get {
                return ResourceManager.GetString("Msg_Not_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row to perform the required operation.
        /// </summary>
        internal static string Msg_Not_Selected1 {
            get {
                return ResourceManager.GetString("Msg_Not_Selected1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only numeric values.
        /// </summary>
        internal static string Msg_Numeric_Error {
            get {
                return ResourceManager.GetString("Msg_Numeric_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Function Not Enabled.
        /// </summary>
        internal static string Msg_Print_Error {
            get {
                return ResourceManager.GetString("Msg_Print_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will update the latest approved head count and employee count. Do you want to continue? .
        /// </summary>
        internal static string Msg_Prompt_Reload {
            get {
                return ResourceManager.GetString("Msg_Prompt_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving! &lt;br/&gt; Please Retry...
        /// </summary>
        internal static string Msg_SavError {
            get {
                return ResourceManager.GetString("Msg_SavError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already modified by another user. Please check for the updated information and try again to update.
        /// </summary>
        internal static string Msg_SavError_Concurrent {
            get {
                return ResourceManager.GetString("Msg_SavError_Concurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving! &lt;br/&gt; Please Retry...
        /// </summary>
        internal static string Msg_Save_Error {
            get {
                return ResourceManager.GetString("Msg_Save_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already modified by another user. Please check for the updated information and try again to update.
        /// </summary>
        internal static string Msg_Save_Error_Concurrent {
            get {
                return ResourceManager.GetString("Msg_Save_Error_Concurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} saved successfully.
        /// </summary>
        internal static string Msg_Save_Success {
            get {
                return ResourceManager.GetString("Msg_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} saved successfully.
        /// </summary>
        internal static string Msg_SavSuccess {
            get {
                return ResourceManager.GetString("Msg_SavSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLServer error occurred.
        /// </summary>
        internal static string Msg_Sql_Error {
            get {
                return ResourceManager.GetString("Msg_Sql_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No Grade].
        /// </summary>
        internal static string NoGrade {
            get {
                return ResourceManager.GetString("NoGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print1 {
            get {
                return ResourceManager.GetString("Print1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege.
        /// </summary>
        internal static string Privilege {
            get {
                return ResourceManager.GetString("Privilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review History.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm.
        /// </summary>
        internal static string TitlConfirmation {
            get {
                return ResourceManager.GetString("TitlConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TitlError {
            get {
                return ResourceManager.GetString("TitlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm.
        /// </summary>
        internal static string Title_Confirmation {
            get {
                return ResourceManager.GetString("Title_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Title_Information {
            get {
                return ResourceManager.GetString("Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TitlInformation {
            get {
                return ResourceManager.GetString("TitlInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Screen.
        /// </summary>
        internal static string ToggleScreen {
            get {
                return ResourceManager.GetString("ToggleScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
