//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ERPManagerRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ERPManagerRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERPManager.ERPManagerRes", typeof(ERPManagerRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asc.
        /// </summary>
        internal static string ascending {
            get {
                return ResourceManager.GetString("ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateRangeException.
        /// </summary>
        internal static string DateRangeException {
            get {
                return ResourceManager.GetString("DateRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to desc.
        /// </summary>
        internal static string descending {
            get {
                return ResourceManager.GetString("descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despatch update failed.
        /// </summary>
        internal static string DespatchUpdateFailed {
            get {
                return ResourceManager.GetString("DespatchUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditConcurrencyException.
        /// </summary>
        internal static string EditConcurrencyException {
            get {
                return ResourceManager.GetString("EditConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO quanitity is less than Container Release quantity.&lt;br/&gt; First change Container release.
        /// </summary>
        internal static string Err_DoQtyLessThanContainerRelease {
            get {
                return ResourceManager.GetString("Err_DoQtyLessThanContainerRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromToRangeException.
        /// </summary>
        internal static string FromToRangeException {
            get {
                return ResourceManager.GetString("FromToRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemExistException.
        /// </summary>
        internal static string ItemExistException {
            get {
                return ResourceManager.GetString("ItemExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManyItemException.
        /// </summary>
        internal static string ManyItemException {
            get {
                return ResourceManager.GetString("ManyItemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string MoreAutoComplete {
            get {
                return ResourceManager.GetString("MoreAutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoItemException.
        /// </summary>
        internal static string NoItemException {
            get {
                return ResourceManager.GetString("NoItemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutofStockException.
        /// </summary>
        internal static string OutofStockException {
            get {
                return ResourceManager.GetString("OutofStockException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordAlreadyExistsException.
        /// </summary>
        internal static string RecordAlreadyExistsException {
            get {
                return ResourceManager.GetString("RecordAlreadyExistsException", resourceCulture);
            }
        }
    }
}
